# Generated by Django 4.0.5 on 2023-08-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0005_alter_audition_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audition',
            new_name='Audition_Reg',
        ),
    ]
