# Generated by Django 4.0.5 on 2023-08-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0006_rename_audition_audition_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition_reg',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
