# Generated by Django 4.0.5 on 2023-08-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0007_alter_audition_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition_reg',
            name='date',
            field=models.DateField(),
        ),
    ]
