# Generated by Django 4.0.5 on 2023-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.FileField(upload_to='media/Registration/'),
        ),
    ]
